
module.exports = Object.freeze({

	e_TVAMain:			"TVAMain",
	e_ProgramInformationTable: "ProgramInformationTable",
	e_ProgramLocationTable: "ProgramLocationTable",
	e_GroupInformationTable: "GroupInformationTable",

	e_ActualStartTime:	"ActualStartTime",
	e_AspectRatio:		"AspectRatio",
	e_AVAttributes:		"AVAttributes",
	e_AudioAttributes:	"AudioAttributes", 
	e_AudioLanguage:	"AudioLanguage",
	e_AuxiliaryUri:		"AuxiliaryUri",
	e_AuxiliaryURL:		"AuxiliaryURL",
	e_BasicDescription:	"BasicDescription",
	e_BitRate:			"Bitrate",
	e_CaptioningAttributes: "CaptioningAttributes",	
	e_CaptionLanguage:	"CaptionLanguage",
	e_Character:		"Character",
	e_Coding:			"Coding",
	e_CreditsItem:		"CreditsItem",
	e_CreditsList:		"CreditsList",
	e_DeliveryMode:		"DeliveryMode",
	e_EndOfAvailability:"EndOfAvailability",
	e_EpisodeOf:		"EpisodeOf",
	e_ExplanatoryText:	"ExplanatoryText",
	e_FamilyName:		"FamilyName",
	e_FirstShowing:		"FirstShowing",
	e_Format:			"Format",
	e_Free:				"Free",
	e_Genre:			"Genre",
	e_GivenName:		"GivenName",
	e_GroupInformation:	"GroupInformation",
	e_GroupType:		"GroupType",
	e_HorizontalSize:	"HorizontalSize", 
	e_HowRelated: 		"HowRelated",
	e_InstanceDescription:"InstanceDescription",
	e_Keyword:			"Keyword",
	e_MediaLocator:		"MediaLocator",
	e_MediaUri:			"MediaUri",
	e_MemberOf:			"MemberOf",
	e_MinimumAge:		"MinimumAge",
	e_Mixtype:			"MixType",
	e_OnDemandProgram:	"OnDemandProgram",
	e_OrganizationName:	"OrganizationName",
	e_OtherIdentifier:	"OtherIdentifier",
	e_ParentalGuidance:	"ParentalGuidance",
	e_ParentalRating:	"ParentalRating",
	e_PersonName:		"PersonName",
	e_ProgramDescription: "ProgramDescription",
	e_ProgramInformation:"ProgramInformation",
	e_Program:			"Program",
	e_ProgramURL:		"ProgramURL",
	e_PublishedDuration:"PublishedDuration",
	e_PublishedStartTime:"PublishedStartTime",
	e_RelatedMaterial: 	"RelatedMaterial",
	e_ScheduleEvent:	"ScheduleEvent",
	e_SignLanguage:		"SignLanguage",
	e_StartOfAvailability:"StartOfAvailability",
	e_StillPictureFormat:"StillPictureFormat",
	e_Synopsis:			"Synopsis",
	e_Title:			"Title",
	e_VerticalSize:		"VerticalSize", 
	e_VideoAttributes:	"VideoAttributes", 
	
	a_crid:				"crid",
	a_length:			"length",
	v_lengthLong:		"long",
	
	a_type:				"type",
	a_href:				"href",
	a_role:				"role",
	a_contentType:		"contentType",
	a_horizontalSize:	"horizontalSize",
	a_verticalSize:		"verticalSize",
	a_programId:		"programId",
	a_groupId:			"groupId",
	a_ordered:			"ordered",
	a_numOfItems:		"numOfItems",
	a_serviceIDRef:		"serviceIDRef",
	a_start:			"start",
	a_end:				"end",
	a_index:			"index",
	a_value:			"value",
	a_purpose:			"purpose",
	a_closed:			"closed",
	
	t_MemberOfType:		"MemberOfType",
	t_ProgramGroupTypeType:"ProgramGroupTypeType",
	
	__zzzTVAENDzzz__: null
});