
module.exports = Object.freeze({

	e_ProgramInformationTable: "ProgramInformationTable",

	e_RelatedMaterial: 	"RelatedMaterial",
	e_HowRelated: 		"HowRelated",
	e_Synopsis:			"Synopsis",
	e_Keyword:			"Keyword",
	e_Genre:			"Genre",
	e_ParentalGuidance:	"ParentalGuidance",
	e_MinimumAge:		"MinimumAge",
	e_ParentalRating:	"ParentalRating",
	e_ExplanatoryText:	"ExplanatoryText",
	e_GivenName:		"GivenName",
	e_FamilyName:		"FamilyName",
	e_PersonName:		"PersonName",
	e_Character:		"Character",
	e_OrganizationName:	"OrganizationName",
	e_CreditsList:		"CreditsList",
	e_CreditsItem:		"CreditsItem",
	e_AuxiliaryURI:		"AuxiliaryURI",
	e_MediaLocator:		"MediaLocator",
	e_Format:			"Format",
	e_StillPictureFormat:"StillPictureFormat",
	e_MediaURI:			"MediaURI",
	e_Title:			"Title",
	e_BasicDescription:	"BasicDescription",
	e_ProgramInformation:"ProgramInformation",
	e_GroupInformation:	"GroupInformation",
	e_OtherIdentifier:	"OtherIdentifier",
	e_MemberOf:			"MemberOf",
	e_EpisodeOf:		"EpisodeOf",
	e_ProgramDescription: "ProgramDescription",
	
	a_crid:				"crid",
	a_length:			"length",
	v_lengthLong:		"long",
	
	a_type:				"type",
	a_href:				"href",
	a_role:				"role",
	a_contentType:		"contentType",
	a_horizontalSize:	"horizontalSize",
	a_verticalSize:		"verticalSize",
	a_programId:		"programId",
	a_groupId:			"groupId",
	a_ordered:			"ordered",
	a_numOfItems:		"numOfItems",
	a_serviceIDRef:		"serviceIDRef",
	a_index:			"index",
	
	t_MemberOfType:		"MemberOfType",
	__zzzTVAENDzzz__: null
});